import numpy as np
from astropy.io import fits

def calibrate_light_frame(light_path, dark_path, bias_path, output_path):
    """
    Subtracts master bias and pure thermal master dark
    from a target star frame.
    """
    # 1. Open FITS image arrays
    with fits.open(light_path) as hdul_light:
        light_data = hdul_light.data.astype(np.float64)
        light_header = hdul_light.header

    with fits.open(dark_path) as hdul_dark:
        dark_data = hdul_dark.data.astype(np.float64)

    with fits.open(bias_path) as hdul_bias:
        bias_data = hdul_bias.data.astype(np.float64)

        # 2. Isolate thermal noise: Dark frames contain bias, subtract first
        pure_thermal_dark = dark_data - bias_data

        # 3. Clean the starlight data array
        calibrated_data = light_data - bias_data - pure_thermal_dark

        # 4. Data Safety: Clip negative values generated by noise artifact to zero
        calibrated_data = np.clip(calibrated_data, a_min=0, a_max=None)

        # 5. Write out the calibrated array preserving original header data
        new_hdu = fits.PrimaryHDU(data=calibrated_data, header=light_header)
        new_hdu.writeto(output_path, overwrite=True)
        print(f"[CALIBRATED] clean data generated: {output_path}")